spring:
  aplication:
    name: db-coffeetime
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: userCoffee
    password: userCoffee
  liquibase:
    change-log: classpath:/config/liquibase/master.xml