spring:
  application:
    name: db-coffeetime

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: userCoffee
    password: userCoffee
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: grupo5coffee@gmail.com
    password: "grupo5senha"
    properties:
      mail:
        stmp:
          ssl:
            enabled: true
          socketFactory:
            port: 587
            fallback: false
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true
          quitwait: false

application:
  email:
    endereco-remetente:
    nome-remetente: CoffeeTime
