spring:
  application:
    name: db-coffeetime

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: userCoffee
    password: userCoffee
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
  mail:
<<<<<<< HEAD
    host: smtp_gmail.com
    port: 587
    username: matheus1995@gmail.com
    password:
      properties:
        email:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
            quitwait: false

  aplication:
    email:
      endereco-remetente: mhateus1995@gmail.com
      nome-remetente:
=======
    host: smtp.gmail.com
    port: 587
    username: grupo5@gmail.com
    password: "102030"
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true
          quitwait: false

application:
  email:
    endereco-remetente:
    nome-remetente: CoffeeTime
>>>>>>> 9e3cd96a01ffec9bd1a957b4a353b0a5b11953e3
